// Real 3rd Semester B.Tech Timetable Data Source of Truth (2026-27)
// Effective From: 20-07-2026

export const realTimetableEntries = [
  // ==================== CSE (Room 109) ====================
  // MONDAY
  {
    id: 'tt_cse_mon_1',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_mon_2',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_mon_3',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'OOPS',
    code: 'CSE-302',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_mon_5',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'DS Lab',
    code: 'CSE-301L',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // TUESDAY
  {
    id: 'tt_cse_tue_1',
    day: 'Tuesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'OOPS',
    code: 'CSE-302',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_tue_2',
    day: 'Tuesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'PYTHON',
    code: 'CSE-303',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_tue_3',
    day: 'Tuesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_tue_4',
    day: 'Tuesday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_tue_5',
    day: 'Tuesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_tue_6',
    day: 'Tuesday',
    roomNo: 'LAB',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'Python Lab',
    code: 'CSE-303L',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // WEDNESDAY
  {
    id: 'tt_cse_wed_1',
    day: 'Wednesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_wed_2',
    day: 'Wednesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_wed_3',
    day: 'Wednesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'PYTHON',
    code: 'CSE-303',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_wed_4',
    day: 'Wednesday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_wed_5',
    day: 'Wednesday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'OOPS',
    code: 'CSE-302',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_wed_6',
    day: 'Wednesday',
    roomNo: 'LAB',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'OOPS Lab',
    code: 'CSE-302L',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // THURSDAY
  {
    id: 'tt_cse_thu_1',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'PYTHON',
    code: 'CSE-303',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_2',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_3',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_4',
    day: 'Thursday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_5',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'Sports/Yoga',
    code: 'SY-301',
    teacher: 'NF-1',
    faculty: 'NF-1',
    classType: 'Sports/Yoga',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_6',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    time: '2-3 PM',
    subject: 'LIB',
    code: 'LIB-301',
    teacher: 'NF-1',
    faculty: 'NF-1',
    classType: 'Library',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_thu_7',
    day: 'Thursday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '03:00 PM',
    endTime: '04:00 PM',
    time: '3-4 PM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // FRIDAY
  {
    id: 'tt_cse_fri_1',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'OOPS',
    code: 'CSE-302',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_2',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_3',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_4',
    day: 'Friday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_5',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'PYTHON',
    code: 'CSE-303',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_6',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    time: '2-3 PM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_fri_7',
    day: 'Friday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '03:00 PM',
    endTime: '04:00 PM',
    time: '3-4 PM',
    subject: 'LIB',
    code: 'LIB-301',
    teacher: 'NF-1',
    faculty: 'NF-1',
    classType: 'Library',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // SATURDAY
  {
    id: 'tt_cse_sat_1',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_2',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'OOPS',
    code: 'CSE-302',
    teacher: 'AKB',
    faculty: 'AKB',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_3',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'PYTHON',
    code: 'CSE-303',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_4',
    day: 'Saturday',
    roomNo: '-',
    branch: 'CSE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_5',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_6',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    time: '2-3 PM',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cse_sat_7',
    day: 'Saturday',
    roomNo: '109',
    branch: 'CSE',
    startTime: '03:00 PM',
    endTime: '04:00 PM',
    time: '3-4 PM',
    subject: 'Sports/Yoga',
    code: 'SY-301',
    teacher: 'NF-1',
    faculty: 'NF-1',
    classType: 'Sports/Yoga',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== CSEDS (Room 109 / 208) ====================
  // MONDAY
  {
    id: 'tt_cseds_mon_1',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSEDS',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'PYTHON',
    code: 'DS-301',
    teacher: 'AM',
    faculty: 'AM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cseds_mon_2',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSEDS',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'P in IoT',
    code: 'DS-302',
    teacher: 'SLM',
    faculty: 'SLM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cseds_mon_3',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSEDS',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cseds_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'CSEDS',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cseds_mon_5',
    day: 'Monday',
    roomNo: '109',
    branch: 'CSEDS',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'DS',
    code: 'CSE-301',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_cseds_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'CSEDS',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'DS Lab',
    code: 'CSE-301L',
    teacher: 'SSM',
    faculty: 'SSM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== ECE (Room 208) ====================
  // MONDAY
  {
    id: 'tt_ece_mon_1',
    day: 'Monday',
    roomNo: '208',
    branch: 'ECE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'DE',
    code: 'ECE-301',
    teacher: 'SS',
    faculty: 'SS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ece_mon_2',
    day: 'Monday',
    roomNo: '208',
    branch: 'ECE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'ECA',
    code: 'ECE-302',
    teacher: 'BKM',
    faculty: 'BKM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ece_mon_3',
    day: 'Monday',
    roomNo: '208',
    branch: 'ECE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'ADEC',
    code: 'ECE-303',
    teacher: 'RS',
    faculty: 'RS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ece_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'ECE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ece_mon_5',
    day: 'Monday',
    roomNo: '208',
    branch: 'ECE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ece_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'ECE',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'ECA Lab',
    code: 'ECE-302L',
    teacher: 'BKM',
    faculty: 'BKM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== EE (Room 310) ====================
  // MONDAY
  {
    id: 'tt_ee_mon_1',
    day: 'Monday',
    roomNo: '310',
    branch: 'EE',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'EM-I',
    code: 'EE-301',
    teacher: 'RD',
    faculty: 'RD',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ee_mon_2',
    day: 'Monday',
    roomNo: '310',
    branch: 'EE',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'ECA',
    code: 'EE-302',
    teacher: 'BKM',
    faculty: 'BKM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ee_mon_3',
    day: 'Monday',
    roomNo: '310',
    branch: 'EE',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ee_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'EE',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ee_mon_5',
    day: 'Monday',
    roomNo: '310',
    branch: 'EE',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ee_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'EE',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'EM-I Lab',
    code: 'EE-301L',
    teacher: 'RD',
    faculty: 'RD',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== MECH (Room 207) ====================
  // MONDAY
  {
    id: 'tt_mech_mon_1',
    day: 'Monday',
    roomNo: '207',
    branch: 'MECH',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'ETD',
    code: 'ME-301',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mech_mon_2',
    day: 'Monday',
    roomNo: '207',
    branch: 'MECH',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'MOS',
    code: 'ME-302',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mech_mon_3',
    day: 'Monday',
    roomNo: '207',
    branch: 'MECH',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mech_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'MECH',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mech_mon_5',
    day: 'Monday',
    roomNo: '207',
    branch: 'MECH',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mech_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'MECH',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'ETD Lab',
    code: 'ME-301L',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== CIVIL (Room 305) ====================
  // MONDAY
  {
    id: 'tt_civil_mon_1',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'MOS',
    code: 'CE-301',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_civil_mon_2',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'IPMEM',
    code: 'CE-302',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_civil_mon_3',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_civil_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'CIVIL',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_civil_mon_5',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_civil_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'CIVIL',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'Building Drawing Practice Lab',
    code: 'CE-301L',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== CIVIL & ENV (Room 305) ====================
  {
    id: 'tt_ceenv_mon_1',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL & ENV',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'IPMEM',
    code: 'CE-302',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ceenv_mon_2',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL & ENV',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'MOS',
    code: 'CE-301',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ceenv_mon_3',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL & ENV',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ceenv_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'CIVIL & ENV',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ceenv_mon_5',
    day: 'Monday',
    roomNo: '305',
    branch: 'CIVIL & ENV',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_ceenv_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'CIVIL & ENV',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'Building Drawing Practice Lab',
    code: 'CE-301L',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== AERO (Room 207 / 310) ====================
  {
    id: 'tt_aero_mon_1',
    day: 'Monday',
    roomNo: '207',
    branch: 'AERO',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'AE',
    code: 'AE-301',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_aero_mon_2',
    day: 'Monday',
    roomNo: '207',
    branch: 'AERO',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'FME',
    code: 'ME-303',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_aero_mon_3',
    day: 'Monday',
    roomNo: '207',
    branch: 'AERO',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_aero_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'AERO',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_aero_mon_5',
    day: 'Monday',
    roomNo: '207',
    branch: 'AERO',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_aero_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'AERO',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'AE Lab',
    code: 'AE-301L',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== AGRI (Room 305 / 208) ====================
  {
    id: 'tt_agri_mon_1',
    day: 'Monday',
    roomNo: '305',
    branch: 'AGRI',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'FME',
    code: 'ME-303',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_agri_mon_2',
    day: 'Monday',
    roomNo: '305',
    branch: 'AGRI',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'IPMEM',
    code: 'CE-302',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_agri_mon_3',
    day: 'Monday',
    roomNo: '305',
    branch: 'AGRI',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_agri_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'AGRI',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_agri_mon_5',
    day: 'Monday',
    roomNo: '305',
    branch: 'AGRI',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_agri_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'AGRI',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'MT Lab',
    code: 'ME-301L',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },

  // ==================== M&M (Room 207 / 310) ====================
  {
    id: 'tt_mm_mon_1',
    day: 'Monday',
    roomNo: '207',
    branch: 'M&M',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    time: '9-10 AM',
    subject: 'MOS',
    code: 'ME-302',
    teacher: 'SPS',
    faculty: 'SPS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mm_mon_2',
    day: 'Monday',
    roomNo: '207',
    branch: 'M&M',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    time: '10-11 AM',
    subject: 'FME',
    code: 'ME-303',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mm_mon_3',
    day: 'Monday',
    roomNo: '207',
    branch: 'M&M',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    time: '11-12 NOON',
    subject: 'MATH-III',
    code: 'BS-301',
    teacher: 'MKS',
    faculty: 'MKS',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mm_mon_4',
    day: 'Monday',
    roomNo: '-',
    branch: 'M&M',
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    time: '12-1 PM',
    subject: 'LUNCH BREAK',
    code: 'LUNCH',
    teacher: '-',
    faculty: '-',
    classType: 'Lunch Break',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mm_mon_5',
    day: 'Monday',
    roomNo: '207',
    branch: 'M&M',
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    time: '1-2 PM',
    subject: 'ENGG. ECO',
    code: 'HS-301',
    teacher: 'CKP',
    faculty: 'CKP',
    classType: 'Lecture',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  },
  {
    id: 'tt_mm_mon_6',
    day: 'Monday',
    roomNo: 'LAB',
    branch: 'M&M',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    time: '2-4 PM',
    subject: 'MT Lab',
    code: 'ME-301L',
    teacher: 'GM',
    faculty: 'GM',
    classType: 'Lab',
    semester: '3rd Semester',
    course: 'B.Tech',
    academicYear: '2026-27',
    effectiveFrom: '20-07-2026',
    status: 'Verified'
  }
];
